name: deploy_tencent_sls

on:
  workflow_dispatch: #手动触发

env:
  TENCENT_SECRET_ID: ${{secrets.TENCENT_SECRET_ID}}
  TENCENT_SECRET_KEY: ${{secrets.TENCENT_SECRET_KEY}}
  SERVERLESS_PLATFORM_VENDOR: tencent

jobs:
  deploy-bilibili-tool:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    environment: Production

    steps:
      # 设置服务器时区为东八区
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      # 检出
      - name: Checkout
        uses: actions/checkout@v2

      # 环境
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # 安装依赖
      - name: Install dependencies
        timeout-minutes: 5
        run: |
          npm install -g typescript serverless
          npm install

      # 构建应用
      - name: Build APP
        run: npm run build

      - name: create config.json file
        timeout-minutes: ${{secrets.TIMEOUT_MINUTES || 15}} # 超时时间(分钟)
        run: |
          if [ -z "$TENCENT_SECRET_ID" ]; then
          echo "部署至腾讯云需要填写TENCENT_SECRET_ID和TENCENT_SECRET_KEY两个secrets"
          exit -1
          fi
          string="${{ secrets.BILI_CONFIG }}"
          if [ -n "$string" ]; then
          echo "$string" >> ./config/config.txt
          echo "成功将secrets(BILI_CONFIG)内容输出到配置文件config.txt"
          node ./tools/processConfig.js
          echo "成功转换成config.json"
          exit 0
          fi

      - name: deploy muilt user
        run: npm run deploy:muilt

      - name: Invoke SCF
        env:
          SCF_SKIP_FIRST_RUN: ${{ secrets.SCF_SKIP_FIRST_RUN }}
        if: ${{ env.SCF_SKIP_FIRST_RUN != 'true'}}
        run: node tools/scfRunAll.js
