name: gh-release

on:
  workflow_dispatch: # 手动触发
  push:
    tags:
      - 'v*'

jobs:
  build:
    if: github.repository == 'catlair/BiliTools'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    environment: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        timeout-minutes: 5
        run: |
          npm install -g typescript modclean
          npm install
      - name: Build APP
        run: npm run build
      - name: ZIP
        run: |
          npm prune --production
          modclean -r -a "*.md,*LICENSE*,.github,.nycrc,*.ts,*.html,*.txt,*.js.map,*.mjs.map,browser.js,@types"
          node tools/pkgclean.js
          mv node_modules dist/node_modules
          cd dist
          zip -r -q tencent_scf.zip *
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/tencent_scf.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
